server:
  port: 8080
  servlet:
    context-path: /scorelens
spring:
  datasource:
    url: "jdbc:mysql://${DB_USERNAME}:${DB_HOST}:${DB_PORT}/${DB_NAME}?ssl-mode=REQUIRED"
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  web:
    resources:
      add-mappings: true
  config:
    import:
  jpa:
    hibernate:
      ddl-auto: update
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
springdoc:
  swagger-ui:
    path: /swagger-ui.html

