server:
  port: 8080
  servlet:
    context-path: /scorelens
spring:
# 
  web:
    resources:
      add-mappings: true
  config:
    import:
  jpa:
    hibernate:
      ddl-auto: update
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
springdoc:
  swagger-ui:
    path: /swagger-ui.html

