server:
  port: 8080
  servlet:
    context-path: /scorelens
spring:
  config:
    import:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

